//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskNetSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int IDMantenimiento { get; set; }
        public Nullable<int> IDTicket { get; set; }
        public string IDUsuario { get; set; }
        public string IDUsuarioAsignado { get; set; }
        public Nullable<int> IDComponente { get; set; }
        public string Asignacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> HoraEntrada { get; set; }
        public string Estado { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
