//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskNetSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public int IDResolucion { get; set; }
        public Nullable<int> IDTicket { get; set; }
        public string Resolucion { get; set; }
        public string Estado { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
